### ISSUE TITLE
Question: Does it handle the case of multiple games on the same day, or games that are less than a week apart?

### ISSUE THREAD

**Issue by Haliboot** [random-parts/Team-Sports-RSVP#18]
Will it send email for all relevant games, or will the soonest game "hide" the other games? I haven't tested this, but it seemed like a case that could easily be overlooked, so I thought I'd ask.

**Comment by random-parts** [comment]
It will send an email for each game in the next/upcoming day a game is scheduled for. That would be a problem for games scheduled less than two days apart as they would not get an email at all. The first game would block it.  https://github.com/random-parts/Team-Sports-RSVP/blob/a506f5eccebc152c55871329bf7004c5e3fc8ad7/src/services/ScheduleService.js#L149-L190

What do you think about a change to have the emailer send emails to _any game_ that is 3 days out [and/or 1, 2 days (this will be adjustable once a settings UI is in place)] , instead of just finding the next game day.  Would probably simplify the task as well.

**Comment by Haliboot** [comment]
Yes, that would be the right thing to do.
Thanks,
- James
