### ISSUE TITLE
It would be nice if it sent an email on weeks with no game, saying "no game"

### ISSUE THREAD

**Issue by Haliboot** [random-parts/Team-Sports-RSVP#7]

**Comment by random-parts** [comment]
Trying to find a suitable way to work this out - taking into account that not all games are 7 days apart. Looking at the overall schedules, some weekday teams get scheduled on the weekend or different days then usual. Currently, I have it checking that there is not a game within the next 11 days ` days_between_games >= 10  ` and will schedule a bye week email when that comes up. The problem is the following scenario(or similar): 

- There is a Team game on Monday, [week 1, day 1]
- the next Monday, [week 2, day 8] is a holiday
- so, the game is scheduled for [week 2 day 12] (Friday)

it's still week 2, but the days between games is 11. 

Would that still call for a bye-week email? What should the check be? What is the cut-off? 
[I feel like I may be missing something here]

Its purely a subjective perspective on what constitutes a week or bye-week (as it relates in this context). What if the game were scheduled for Sunday instead of Friday? Is Sunday the start of a new week or is Monday? If its based purely off a US calendar that is stuck in the dark ages - the week starts on Sunday - and would not make sense to anyone else. 

Was thinking about a `Next Game` email, sent a day or two after a game is played? An email with the DateTime of the next upcoming game, sent to all roster members wether or not they rsvp'd. Could add a `days until next team game` stat along with the DateTime. This  option really seems a bit redundant with rsvp emails that also go out.

I like a `bye-week` email idea better, as it is more brain bandwidth efficient - but without absolute days between games, the script would have to make an assumption that everyone views something, as ambiguous as time, the same way. 

Ideas?

**Comment by Haliboot** [comment]
Good points.

How about this: Scan all the game days in the schedule for their
day-of-the-week. The most often occurring day-of-the-week is considered the
normal team game day. Send an email three or four days in advance any time
that day-of-the-week doesn't have a game on it and the date lies within the
bounds of the season.. Example: "FYI: No Walking Dead game scheduled for
Friday 9-15-17". No need to claim or determine if it is really a
"bye-week".

- James

**Comment by random-parts** [comment]
That would work for most soccerZone leagues, since they are grouped by day-of-the-week. 

What about leagues that play on random days of the week? or are alternately scheduled on either [Tuesday or Wednesday] for example?  I think I remember some of the soccerZone youth leagues playing on either a Saturday or Sunday, or maybe both.

**Comment by Haliboot** [comment]
I'd say just disable the feature if there isn't a day on which a certain
fraction (1/2? 2/3?) of games are scheduled. People in those leagues are
probably not strongly assuming there is a game on a certain day every week.
