### ISSUE TITLE
Noticed funny behavior regarding email text

### ISSUE THREAD

**Issue by Haliboot** [random-parts/Team-Sports-RSVP#8]
FYI: On one of my teams, I had put "lewis (keeper)" on row 19 under the column for Game 5.  When it sent the email for game 6, it asked "will you be attending the lewis (keeper) game?".  Rows 17 and 18 were blank.

I noticed that for some reason, unlike other sheets, I had a blank row 5. I deleted it now, so I'll see if anything else funny happens or not.

**Comment by random-parts** [comment]
I have not been able to reproduce this. The value that displayed `lewis (keeper)` in the email is retrieved in this way:

https://github.com/random-parts/Team-Sports-RSVP/blob/31333a57e59d7d4a4d78e589f56c437d5d5f72df/src/services/EmailService.js#L71
https://github.com/random-parts/Team-Sports-RSVP/blob/31333a57e59d7d4a4d78e589f56c437d5d5f72df/src/beans/TeamBean.js#L34
https://github.com/random-parts/Team-Sports-RSVP/blob/31333a57e59d7d4a4d78e589f56c437d5d5f72df/src/beans/TeamBean.js#L42
https://github.com/random-parts/Team-Sports-RSVP/blob/31333a57e59d7d4a4d78e589f56c437d5d5f72df/src/beans/SheetBean.js#L94

Not sure how it could have taken the value of `J19` instead of the value from `A1`. 
There does seem to be an issue with `dataValidation` being set on the sheet, as the value `lewis (keeper)` should not have been allowed to be entered into that location.
